export const SET_USER = 'SET_USER'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'

export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const GET_ORPHANAGES = 'GET_ORPHANAGES'
export const GET_ORPHANAGE = 'GET_ORPHANAGE'
export const CLEAR_ORPHANAGE = 'CLEAR_ORPHANAGE'